### ISSUE TITLE
命名空间访问

### ISSUE THREAD

**Issue by putiyang** [huanwei/rocketmq-operator#42]
**Describe your support request, or any question relating to RocketMQ Operator**:
rocketmq-operator  namesapce 的service 能被其它 namespace 访问么,多环境下只想部署一个mq集群

/triage support

**Comment by huanwei** [comment]
@putiyang 这种情况下最简单的方式你可以将它部署在kube-system namespace下。

**Comment by huanwei** [comment]
I will close this issue @putiyang
