### ISSUE TITLE
Error: ImagePullBackOff

### ISSUE THREAD

**Issue by MagicStarTrace** [huanwei/rocketmq-operator#46]
![image](https://user-images.githubusercontent.com/15685376/64417241-4ec54380-d0cb-11e9-88e4-b4f8136b35a7.png)

This looks like a private image. Why would it always pull?

**Comment by huanwei** [comment]
> ![image](https://user-images.githubusercontent.com/15685376/64417241-4ec54380-d0cb-11e9-88e4-b4f8136b35a7.png)
> 
> This looks like a private image. Why would it always pull?

@huyifanstar Which version do you use? The latest version should be huanwei/rocketmq-operator:0.1.3

**Comment by huanwei** [comment]
I will close this issue @huyifanstar
