### ISSUE TITLE
启动operator错误

### ISSUE THREAD

**Issue by hppx5456** [huanwei/rocketmq-operator#48]
使用kubectl delete -f deploy/03-deploymentWithConfig.yaml后
ocketmq-operator   rocketmq-operator-5657b85cf9-kxjv7   0/1     Pending   0
使用kubectl describe pod rocketmq-operator-5657b85cf9-kxjv7后
发现Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 3 node(s) didn't match node selector.

**Comment by huanwei** [comment]
@hppx5456 将operator的yaml中nodeSelector相关配置去掉。

**Comment by hppx5456** [comment]
嗯，解决了，谢谢🙏
